version: "3"

services:

  app:
    image: cbsanjaya/laravel:app
    volumes:
      - ${APP_SRC}:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - cache
    networks:
      - backend
      - frontend

  db:
    image: cbsanjaya/laravel:db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}
    volumes:
      - db:/var/lib/mysql
      - $MYSQL_BACKUP_DIR:/backup
    networks:
      - backend

  dbadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - dbadmin:/sessions
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db
    networks:
      - frontend
      - backend
    
  cache:
    image: redis:alpine
    volumes:
      - cache:/data
    networks:
      - backend

  cacheadmin:
    image: cbsanjaya/laravel:redisadmin
    environment:
      - ADMIN_USER=${REDIS_ADMIN_USER}
      - ADMIN_PASS=${REDIS_ADMIN_PASS}
      - REDIS_1_HOST=cache
      - REDIS_1_PORT=6379
    ports:
      - "${REDIS_ADMIN_PORT}:80"
    depends_on:
      - cache
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  db:
  cache:
  dbadmin: